-- V0001__initial_schema.sql
-- 007 Resort & Spa Integrated Facility Operations Platform — initial schema.
-- MySQL 8.4, InnoDB, utf8mb4. Applied forward-only by the DbUp runner (see
-- src/R007.Infrastructure/Migrations and db/migrations/README.md). Never edit after merge.
--
-- Conventions (architecture/04-database-schema.md, ADR-0003, ADR-0004):
--   * UUIDv7, generated by the API, stored BINARY(16) on sync-sensitive tables.
--   * BIGINT UNSIGNED AUTO_INCREMENT on local, never-synced reference/config tables
--     (capability_type is VARCHAR-keyed; role/permission use surrogate BIGINT keys).
--   * DATETIME(6) UTC for all timestamps.
--   * DECIMAL for money/quantities — none needed by this migration's tables.
--   * VARCHAR + CHECK instead of native ENUM.
--   * row_version INT UNSIGNED for optimistic concurrency on mutable header rows.
--   * Soft delete (deleted_at) only where the row must remain referenceable after removal
--     from view (facility_unit, staff, role_assignment) — never on audit/ledger tables.
--   * Every FK indexed by virtue of being declared; additional composite indexes noted inline.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ============================================================================
-- Organization / facility hierarchy (architecture/03, architecture/05)
-- ============================================================================

CREATE TABLE organization (
  id          BINARY(16) NOT NULL PRIMARY KEY,
  name        VARCHAR(200) NOT NULL,
  created_at  DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at  DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE site (
  id               BINARY(16) NOT NULL PRIMARY KEY,
  organization_id  BINARY(16) NOT NULL,
  name             VARCHAR(200) NOT NULL,
  time_zone        VARCHAR(64) NOT NULL DEFAULT 'Africa/Lagos',
  created_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_site_org FOREIGN KEY (organization_id) REFERENCES organization (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE facility_unit (
  id               BINARY(16) NOT NULL PRIMARY KEY,
  organization_id  BINARY(16) NOT NULL,
  site_id          BINARY(16) NOT NULL,
  parent_id        BINARY(16) NULL,
  code             VARCHAR(64) NOT NULL,
  name             VARCHAR(200) NOT NULL,
  is_active        TINYINT(1) NOT NULL DEFAULT 1,
  deleted_at       DATETIME(6) NULL,
  row_version      INT UNSIGNED NOT NULL DEFAULT 1,
  created_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_fu_org FOREIGN KEY (organization_id) REFERENCES organization (id),
  CONSTRAINT fk_fu_site FOREIGN KEY (site_id) REFERENCES site (id),
  CONSTRAINT fk_fu_parent FOREIGN KEY (parent_id) REFERENCES facility_unit (id),
  CONSTRAINT uq_fu_code UNIQUE (site_id, code),
  INDEX ix_fu_parent (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Fixed catalog, seeded below. Not user-editable at runtime (architecture/05 §2).
CREATE TABLE capability_type (
  code         VARCHAR(48) NOT NULL PRIMARY KEY,
  description  VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE facility_capability (
  id                BINARY(16) NOT NULL PRIMARY KEY,
  facility_unit_id  BINARY(16) NOT NULL,
  capability_code   VARCHAR(48) NOT NULL,
  is_enabled        TINYINT(1) NOT NULL DEFAULT 1,
  created_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_fc_facility FOREIGN KEY (facility_unit_id) REFERENCES facility_unit (id),
  CONSTRAINT fk_fc_capability FOREIGN KEY (capability_code) REFERENCES capability_type (code),
  CONSTRAINT uq_fc UNIQUE (facility_unit_id, capability_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE operating_rule (
  id                      BINARY(16) NOT NULL PRIMARY KEY,
  facility_capability_id  BINARY(16) NOT NULL,
  rule_key                VARCHAR(64) NOT NULL,
  rule_value              VARCHAR(255) NOT NULL,
  created_at              DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at              DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_or_fc FOREIGN KEY (facility_capability_id) REFERENCES facility_capability (id),
  CONSTRAINT uq_or UNIQUE (facility_capability_id, rule_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================================
-- Identity & access (architecture/03, architecture/06, architecture/17)
-- ============================================================================

CREATE TABLE staff (
  id               BINARY(16) NOT NULL PRIMARY KEY,
  organization_id  BINARY(16) NOT NULL,
  site_id          BINARY(16) NOT NULL,
  staff_number     VARCHAR(32) NOT NULL,
  first_name       VARCHAR(120) NOT NULL,
  last_name        VARCHAR(120) NOT NULL,
  email            VARCHAR(255) NULL,
  phone            VARCHAR(32) NULL,
  is_active        TINYINT(1) NOT NULL DEFAULT 1,
  deleted_at       DATETIME(6) NULL,
  row_version      INT UNSIGNED NOT NULL DEFAULT 1,
  created_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_staff_org FOREIGN KEY (organization_id) REFERENCES organization (id),
  CONSTRAINT fk_staff_site FOREIGN KEY (site_id) REFERENCES site (id),
  CONSTRAINT uq_staff_number UNIQUE (site_id, staff_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- One login identity per staff member in Phase 1 (1:1 with staff).
CREATE TABLE user_account (
  id                  BINARY(16) NOT NULL PRIMARY KEY,
  staff_id            BINARY(16) NOT NULL,
  username            VARCHAR(100) NOT NULL,
  is_active           TINYINT(1) NOT NULL DEFAULT 1,
  failed_login_count  INT UNSIGNED NOT NULL DEFAULT 0,
  locked_until        DATETIME(6) NULL,
  row_version         INT UNSIGNED NOT NULL DEFAULT 1,
  created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_ua_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
  CONSTRAINT uq_ua_staff UNIQUE (staff_id),
  CONSTRAINT uq_ua_username UNIQUE (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Schema-ready for PASSWORD (Phase 1), PIN and NFC_CARD/TOTP (future); credential_hash is
-- always a one-way hash (Argon2id for PASSWORD/PIN). Never store a reversible secret here.
CREATE TABLE credential (
  id                BINARY(16) NOT NULL PRIMARY KEY,
  user_account_id   BINARY(16) NOT NULL,
  credential_type   VARCHAR(16) NOT NULL
                      CHECK (credential_type IN ('PASSWORD','PIN','NFC_CARD','TOTP')),
  credential_hash   VARCHAR(512) NOT NULL,
  algorithm         VARCHAR(32) NOT NULL DEFAULT 'ARGON2ID',
  is_active         TINYINT(1) NOT NULL DEFAULT 1,
  last_used_at      DATETIME(6) NULL,
  row_version       INT UNSIGNED NOT NULL DEFAULT 1,
  created_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_cred_account FOREIGN KEY (user_account_id) REFERENCES user_account (id),
  INDEX ix_cred_account_type (user_account_id, credential_type, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Local reference table (never synced) — BIGINT surrogate key per ADR-0003 consequence.
CREATE TABLE role (
  id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code         VARCHAR(64) NOT NULL,
  name         VARCHAR(120) NOT NULL,
  description  VARCHAR(255) NULL,
  created_at   DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at   DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_role_code UNIQUE (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE permission (
  id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code         VARCHAR(96) NOT NULL,
  description  VARCHAR(255) NULL,
  created_at   DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_permission_code UNIQUE (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE role_permission (
  role_id            BIGINT UNSIGNED NOT NULL,
  permission_id      BIGINT UNSIGNED NOT NULL,
  requires_approval  TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (role_id, permission_id),
  CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES role (id),
  CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES permission (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Scopes a role to a staff member at organization, site, or facility_unit level
-- (architecture/06 §1). Sync-sensitive (a site can create assignments independently).
CREATE TABLE role_assignment (
  id                BINARY(16) NOT NULL PRIMARY KEY,
  staff_id          BINARY(16) NOT NULL,
  role_id           BIGINT UNSIGNED NOT NULL,
  scope_level       VARCHAR(16) NOT NULL
                      CHECK (scope_level IN ('ORGANIZATION','SITE','FACILITY_UNIT')),
  organization_id   BINARY(16) NOT NULL,
  site_id           BINARY(16) NULL,
  facility_unit_id  BINARY(16) NULL,
  is_active         TINYINT(1) NOT NULL DEFAULT 1,
  deleted_at        DATETIME(6) NULL,
  granted_by        BINARY(16) NULL,
  granted_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  row_version       INT UNSIGNED NOT NULL DEFAULT 1,
  created_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_ra_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
  CONSTRAINT fk_ra_role FOREIGN KEY (role_id) REFERENCES role (id),
  CONSTRAINT fk_ra_org FOREIGN KEY (organization_id) REFERENCES organization (id),
  CONSTRAINT fk_ra_site FOREIGN KEY (site_id) REFERENCES site (id),
  CONSTRAINT fk_ra_facility FOREIGN KEY (facility_unit_id) REFERENCES facility_unit (id),
  CONSTRAINT fk_ra_granted_by FOREIGN KEY (granted_by) REFERENCES staff (id),
  INDEX ix_ra_staff_active (staff_id, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Refresh-token store. The access token (JWT) is never persisted; the refresh token is
-- opaque and stored only as its SHA-256 hash, so a DB read can never yield a usable token
-- (architecture/17 §3). Revoking a row here revokes "sign out everywhere" immediately.
CREATE TABLE session (
  id                       BINARY(16) NOT NULL PRIMARY KEY,
  user_account_id          BINARY(16) NOT NULL,
  device_id                BINARY(16) NULL,
  refresh_token_hash       CHAR(64) NOT NULL,
  issued_at                DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at               DATETIME(6) NOT NULL,
  revoked_at               DATETIME(6) NULL,
  revoked_reason           VARCHAR(255) NULL,
  replaced_by_session_id   BINARY(16) NULL,
  created_ip               VARCHAR(64) NULL,
  user_agent               VARCHAR(255) NULL,
  row_version              INT UNSIGNED NOT NULL DEFAULT 1,
  created_at               DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at               DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_session_account FOREIGN KEY (user_account_id) REFERENCES user_account (id),
  CONSTRAINT fk_session_replaced_by FOREIGN KEY (replaced_by_session_id) REFERENCES session (id),
  CONSTRAINT uq_session_token_hash UNIQUE (refresh_token_hash),
  INDEX ix_session_account_active (user_account_id, revoked_at, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================================
-- Devices (architecture/03, architecture/14, architecture/17)
-- ============================================================================

CREATE TABLE device (
  id                BINARY(16) NOT NULL PRIMARY KEY,
  organization_id   BINARY(16) NOT NULL,
  site_id           BINARY(16) NOT NULL,
  facility_unit_id  BINARY(16) NULL,
  device_type       VARCHAR(24) NOT NULL
                      CHECK (device_type IN
                        ('POS','TABLET','KDS','SCANNER','PRINTER','BIOMETRIC_TERMINAL','NFC_READER','ADMIN_WEB_CLIENT','OTHER')),
  name              VARCHAR(200) NOT NULL,
  is_active         TINYINT(1) NOT NULL DEFAULT 1,
  is_revoked        TINYINT(1) NOT NULL DEFAULT 0,
  revoked_at        DATETIME(6) NULL,
  row_version       INT UNSIGNED NOT NULL DEFAULT 1,
  created_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at        DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_device_org FOREIGN KEY (organization_id) REFERENCES organization (id),
  CONSTRAINT fk_device_site FOREIGN KEY (site_id) REFERENCES site (id),
  CONSTRAINT fk_device_facility FOREIGN KEY (facility_unit_id) REFERENCES facility_unit (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- One row per issued device credential (device-identity JWT, aud="device"). `token_id` is the
-- JWT's `jti`, checked against `revoked_at` so a compromised device can be shut off even if a
-- still-unexpired token is cached on it (architecture/17 §3).
CREATE TABLE device_registration (
  id                     BINARY(16) NOT NULL PRIMARY KEY,
  device_id              BINARY(16) NOT NULL,
  token_id               BINARY(16) NOT NULL,
  registered_by_staff_id BINARY(16) NULL,
  issued_at              DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at             DATETIME(6) NOT NULL,
  revoked_at             DATETIME(6) NULL,
  revoked_reason         VARCHAR(255) NULL,
  created_at             DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_dr_device FOREIGN KEY (device_id) REFERENCES device (id),
  CONSTRAINT fk_dr_staff FOREIGN KEY (registered_by_staff_id) REFERENCES staff (id),
  CONSTRAINT uq_dr_token UNIQUE (token_id),
  INDEX ix_dr_device_active (device_id, revoked_at, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- A device's current (or historical) placement at a facility/operating point.
CREATE TABLE device_binding (
  id                     BINARY(16) NOT NULL PRIMARY KEY,
  device_id              BINARY(16) NOT NULL,
  facility_unit_id       BINARY(16) NOT NULL,
  operating_point_label  VARCHAR(120) NULL,
  bound_at               DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  unbound_at             DATETIME(6) NULL,
  created_at             DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_db_device FOREIGN KEY (device_id) REFERENCES device (id),
  CONSTRAINT fk_db_facility FOREIGN KEY (facility_unit_id) REFERENCES facility_unit (id),
  INDEX ix_db_device_active (device_id, unbound_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================================
-- Audit & approvals (architecture/04 §3.5, architecture/17 §5)
-- ============================================================================

CREATE TABLE approval (
  id            BINARY(16) NOT NULL PRIMARY KEY,
  requested_by  BINARY(16) NOT NULL,
  approved_by   BINARY(16) NULL,
  status        VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('PENDING','APPROVED','REJECTED')),
  reason        VARCHAR(255) NULL,
  created_at    DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  decided_at    DATETIME(6) NULL,
  CONSTRAINT fk_approval_requested_by FOREIGN KEY (requested_by) REFERENCES staff (id),
  CONSTRAINT fk_approval_approved_by FOREIGN KEY (approved_by) REFERENCES staff (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Append-only, hash-chained. `seq` gives a strict, gap-aware total order so the API can find
-- "the previous row" deterministically under concurrent writers (it locks the max-`seq` row
-- with SELECT ... FOR UPDATE inside the same transaction as the mutation being audited).
-- `prev_hash` of the first row in the chain is 64 zero characters.
CREATE TABLE audit_log (
  seq                 BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id                  BINARY(16) NOT NULL,
  occurred_at         DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  organization_id     BINARY(16) NOT NULL,
  site_id             BINARY(16) NOT NULL,
  actor_staff_id      BINARY(16) NULL,
  facility_unit_id    BINARY(16) NULL,
  operating_point_id  BINARY(16) NULL,
  device_id           BINARY(16) NULL,
  action              VARCHAR(64) NOT NULL,
  entity_type         VARCHAR(64) NOT NULL,
  entity_id           BINARY(16) NOT NULL,
  old_value           JSON NULL,
  new_value           JSON NULL,
  approval_id         BINARY(16) NULL,
  prev_hash           CHAR(64) NOT NULL,
  row_hash            CHAR(64) NOT NULL,
  PRIMARY KEY (seq),
  CONSTRAINT uq_al_id UNIQUE (id),
  CONSTRAINT fk_al_approval FOREIGN KEY (approval_id) REFERENCES approval (id),
  INDEX ix_al_entity (entity_type, entity_id),
  INDEX ix_al_actor (actor_staff_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE security_event (
  id              BINARY(16) NOT NULL PRIMARY KEY,
  occurred_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  event_type      VARCHAR(64) NOT NULL,
  severity        VARCHAR(16) NOT NULL DEFAULT 'INFO'
                    CHECK (severity IN ('INFO','WARNING','CRITICAL')),
  actor_staff_id  BINARY(16) NULL,
  device_id       BINARY(16) NULL,
  ip_address      VARCHAR(64) NULL,
  details         JSON NULL,
  created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX ix_se_type_time (event_type, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================================
-- Idempotency (architecture/04 §1, architecture/15 §1)
-- ============================================================================

CREATE TABLE idempotency_record (
  scope            VARCHAR(64) NOT NULL,
  idempotency_key  VARCHAR(128) NOT NULL,
  request_hash     CHAR(64) NOT NULL,
  response_status  SMALLINT UNSIGNED NOT NULL,
  response_body    JSON NOT NULL,
  created_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (scope, idempotency_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Note: DbUp's default MySQL journal auto-creates and manages its own applied-scripts
-- tracking table (`SchemaVersions`) the first time the runner executes — it is not created
-- by this script. See src/R007.Infrastructure/Migrations/R007MySqlJournal.cs.

-- ============================================================================
-- Seed data — fixed catalogs only (architecture/05 §2, architecture/06 §2). No tenant
-- (organization/site/facility) data is seeded here; that is a deployment-time bootstrap step.
-- ============================================================================

INSERT INTO capability_type (code, description) VALUES
  ('POS', 'Point-of-sale order entry at this facility'),
  ('TABLE_SERVICE', 'Table-based service (assign orders to tables)'),
  ('OPEN_TAB', 'Orders accumulate on an open tab until settled'),
  ('KITCHEN_ROUTING', 'Order lines route to a kitchen KDS station'),
  ('BAR_ROUTING', 'Order lines route to a bar KDS station'),
  ('TICKETING', 'Issues tickets/entitlements'),
  ('TICKET_VALIDATION', 'Validates/redeems tickets or entitlements'),
  ('BOOKING', 'Resource booking / reservations'),
  ('APPOINTMENTS', 'Appointment-style scheduling (spa/salon)'),
  ('CAPACITY_MANAGEMENT', 'Enforces a maximum concurrent occupancy'),
  ('TIME_SLOTS', 'Fixed time-slot scheduling'),
  ('INVENTORY', 'Tracks stock movements/balances for this facility'),
  ('MEMBERSHIP', 'Accepts/validates membership'),
  ('SUBSCRIPTION_BILLING', 'Recurring membership billing'),
  ('USAGE_LIMITS', 'Enforces per-period usage limits'),
  ('MEMBER_DISCOUNTS', 'Applies member pricing/discounts'),
  ('STAFF_ASSIGNMENT', 'Assigns staff to appointments/sessions'),
  ('BARCODE_SALES', 'Barcode-scanned retail sales'),
  ('QR_VALIDATION', 'QR-code based entitlement validation'),
  ('RECEIPT_PRINTING', 'Prints customer receipts'),
  ('PAYMENT_ACCEPTANCE', 'Accepts payment directly at this facility'),
  ('EQUIPMENT_RENTAL', 'Issues and tracks returnable rental equipment');

INSERT INTO role (code, name, description) VALUES
  ('WAIT_STAFF', 'Wait staff', 'Takes and sends orders at table-service facilities'),
  ('BARTENDER', 'Bartender / dispenser', 'Creates bar-routed orders and works the prep ticket queue'),
  ('KITCHEN_STAFF', 'Kitchen staff', 'Works the kitchen prep ticket queue'),
  ('CASHIER', 'Cashier', 'Takes payment and settles orders/tabs'),
  ('STOREKEEPER', 'Storekeeper', 'Receives, transfers and counts inventory'),
  ('UNIT_SUPERVISOR', 'Unit supervisor', 'Approves sensitive actions at facility scope'),
  ('PROCUREMENT', 'Procurement', 'Manages suppliers and purchase receipts'),
  ('ACCOUNTANT', 'Accountant', 'Reconciles settlements and approves refunds/reversals'),
  ('MANAGER', 'Manager', 'Site-scope operational management, staffing and pricing'),
  ('IT_ADMIN', 'IT / system administrator', 'Manages devices, sessions and security — never finance/pricing'),
  ('OWNER', 'Owner / super admin', 'Full access at organization and site scope');

INSERT INTO permission (code, description) VALUES
  ('order.create', 'Create a draft order'),
  ('order.line.add', 'Add a line to a draft order'),
  ('order.line.remove_unsent', 'Remove an unsent line from a draft order'),
  ('order.send', 'Send an order to prep/routing'),
  ('order.void.execute', 'Void an order or line'),
  ('order.void.approve', 'Approve a pending void'),
  ('order.discount.approve', 'Approve a discount above the facility threshold'),
  ('order.price_override.approve', 'Approve a manual price override'),
  ('order.comp.approve', 'Approve a complimentary (comp) item'),
  ('order.settle', 'Settle an order/tab against payment(s)'),
  ('tab.view_own_facility', 'View tabs at the staff member''s own facility'),
  ('prep_ticket.view', 'View the prep ticket queue'),
  ('prep_ticket.transition', 'Transition a prep ticket''s status'),
  ('payment.take', 'Take a payment'),
  ('payment.split', 'Split a payment across tenders'),
  ('payment.reversal.approve', 'Approve a payment reversal'),
  ('cash_session.open', 'Open a cash drawer session'),
  ('cash_session.close', 'Close a cash drawer session'),
  ('receipt.reprint', 'Reprint a customer receipt'),
  ('inventory.receive', 'Record a goods receipt'),
  ('inventory.transfer.create', 'Create a stock transfer'),
  ('inventory.count.create', 'Create a physical stock count'),
  ('inventory.adjustment.request', 'Request a stock adjustment'),
  ('inventory.adjustment.approve', 'Approve a stock adjustment'),
  ('inventory.purchase_receipt.create', 'Create a purchase receipt'),
  ('supplier.manage', 'Manage supplier records'),
  ('finance.report.view', 'View financial reports'),
  ('settlement.reconcile', 'Reconcile a settlement'),
  ('refund.approve', 'Approve a refund'),
  ('staff.manage', 'Manage staff records'),
  ('staff.clock_correction.approve', 'Approve an attendance clock correction'),
  ('role_assignment.manage', 'Grant or revoke role assignments below one''s own level'),
  ('facility.configure', 'Configure facility capabilities/operating rules'),
  ('pricing.manage', 'Manage prices and price lists'),
  ('report.view.all', 'View reports across all facilities'),
  ('device.register', 'Register a device'),
  ('device.revoke', 'Revoke a device'),
  ('device.view', 'View device registrations'),
  ('session.revoke', 'Revoke a staff session'),
  ('security_event.view', 'View security events'),
  ('config.manage', 'Manage system configuration'),
  ('audit.view', 'View the audit trail');

-- Role -> permission bundles (architecture/06 §2). Bundles are additive per the doc's
-- "X bundle + ..." language (e.g. Cashier = wait-staff bundle + payment/settlement permissions).
-- `order.void.execute` is bundled with Cashier: the doc lists void/discount/etc. as separate
-- execute-vs-approve permissions but does not name every execute-side holder explicitly; a
-- cashier is the natural front-line holder of "execute", with Unit supervisor holding
-- "approve" — called out as an interpretation in the PR description.

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM role r, permission p
WHERE r.code = 'WAIT_STAFF' AND p.code IN
  ('order.create','order.line.add','order.line.remove_unsent','order.send','tab.view_own_facility');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM role r, permission p
WHERE r.code = 'BARTENDER' AND p.code IN
  ('order.create','prep_ticket.view','prep_ticket.transition');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM role r, permission p
WHERE r.code = 'KITCHEN_STAFF' AND p.code IN
  ('prep_ticket.view','prep_ticket.transition');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM role r, permission p
WHERE r.code = 'CASHIER' AND p.code IN
  ('order.create','order.line.add','order.line.remove_unsent','order.send','tab.view_own_facility',
   'order.void.execute','payment.take','payment.split','order.settle',
   'cash_session.open','cash_session.close','receipt.reprint');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM role r, permission p
WHERE r.code = 'STOREKEEPER' AND p.code IN
  ('inventory.receive','inventory.transfer.create','inventory.count.create','inventory.adjustment.request');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM role r, permission p
WHERE r.code = 'UNIT_SUPERVISOR' AND p.code IN
  ('order.create','order.line.add','order.line.remove_unsent','order.send','tab.view_own_facility',
   'order.void.execute','payment.take','payment.split','order.settle',
   'cash_session.open','cash_session.close','receipt.reprint',
   'order.void.approve','order.discount.approve','order.price_override.approve','order.comp.approve',
   'inventory.adjustment.approve','staff.clock_correction.approve');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM role r, permission p
WHERE r.code = 'PROCUREMENT' AND p.code IN
  ('inventory.purchase_receipt.create','supplier.manage');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM role r, permission p
WHERE r.code = 'ACCOUNTANT' AND p.code IN
  ('finance.report.view','settlement.reconcile','refund.approve','payment.reversal.approve');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM role r, permission p
WHERE r.code = 'MANAGER' AND p.code IN
  ('order.create','order.line.add','order.line.remove_unsent','order.send','tab.view_own_facility',
   'order.void.execute','payment.take','payment.split','order.settle',
   'cash_session.open','cash_session.close','receipt.reprint',
   'order.void.approve','order.discount.approve','order.price_override.approve','order.comp.approve',
   'inventory.adjustment.approve','staff.clock_correction.approve',
   'staff.manage','role_assignment.manage','facility.configure','pricing.manage','report.view.all');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM role r, permission p
WHERE r.code = 'IT_ADMIN' AND p.code IN
  ('device.register','device.revoke','device.view','session.revoke','security_event.view',
   'config.manage','audit.view');

-- Owner / super admin: every permission.
INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM role r CROSS JOIN permission p
WHERE r.code = 'OWNER';
