<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>R007.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
    <PackageReference Include="dbup-mysql" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\R007.SharedKernel\R007.SharedKernel.csproj" />
  </ItemGroup>

</Project>
